# STRATEGY:
# build docker image each time in Git Actions and push image in Docker Hub
# copy the docker-compose and Caddyfile in EC2 as we need them to run Image (they are not in Image)
# then pull image in EC2, then run
# so we don't need git in EC2 and no docker build... reduces instance load

name: Deploy App to EC2

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'sdk/**'
      - '**.md'
      - '.gitignore'
      - '.dockerignore'
  workflow_dispatch:

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, '[skip-deploy]') && !contains(github.event.head_commit.message, '[no-deploy]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Login Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Image + tag
      - name: Build Docker Image
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/pramaan:latest \
          -t ${{ secrets.DOCKER_USERNAME }}/pramaan:${{ github.sha }} \
          .

      # Push Image
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pramaan:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/pramaan:${{ github.sha }}

      # Setup EC2 directory
      - name: Setup EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /srv/pramaan
            sudo chown -R ubuntu:ubuntu /srv/pramaan

      # Copy files to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml,Caddyfile"
          target: "/srv/pramaan"

      # Deploy in EC2
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /srv/pramaan

            cat <<'EOF' > .env
            NODE_ENV=${{ secrets.NODE_ENV }}
            PORT=${{ secrets.PORT }}
            RUN_SEEDS=${{ secrets.RUN_SEEDS }}

            APP_NAME=${{ secrets.APP_NAME }}
            APP_DOMAIN=${{ secrets.APP_DOMAIN }}
            APP_DOC_URL=${{ secrets.APP_DOC_URL }}

            NEON_PG_DATABASE_URL=${{ secrets.NEON_PG_DATABASE_URL }}
            COOKIE_SECRET=${{ secrets.COOKIE_SECRET }}

            REDIS_URL=${{ secrets.REDIS_URL }}

            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            EMAIL_FROM=${{ secrets.EMAIL_FROM }}

            AUTH_ISSUER=${{ secrets.AUTH_ISSUER }}
            AUTH_CODE_EX=${{ secrets.AUTH_CODE_EX }}
            AUTH_REQUEST_EX=${{ secrets.AUTH_REQUEST_EX }}
            AUTH_TOKENS_EX=${{ secrets.AUTH_TOKENS_EX }}

            ACTIVE_SESSION_EX=${{ secrets.ACTIVE_SESSION_EX }}
            IDENTITY_SESSION_EX=${{ secrets.IDENTITY_SESSION_EX }}

            EMAIL_VERIFICATION_TOKEN_EX=${{ secrets.EMAIL_VERIFICATION_TOKEN_EX }}
            SIGN_VERIFICATION_TOKEN_EX=${{ secrets.SIGN_VERIFICATION_TOKEN_EX }}
            RESET_PASSWORD_EX=${{ secrets.RESET_PASSWORD_EX }}

            MAX_SIGNIN_FAILURES=${{ secrets.MAX_SIGNIN_FAILURES }}
            SIGNIN_LOCK_UNTIL=${{ secrets.SIGNIN_LOCK_UNTIL }}
            SIGN_IN_FAIL_COUNT_EX=${{ secrets.SIGN_IN_FAIL_COUNT_EX }}

            CLIENT_CACHE_EX=${{ secrets.CLIENT_CACHE_EX }}
            CLIENT_SECRET_KEY=${{ secrets.CLIENT_SECRET_KEY }}
            PROFILE_CACHE_EX=${{ secrets.PROFILE_CACHE_EX }}

            KEY_ENC_SECRET=${{ secrets.KEY_ENC_SECRET }}
            INIT_ADMIN_EMAIL=${{ secrets.INIT_ADMIN_EMAIL }}
            LOGTAIL_SOURCE_TOKEN=${{ secrets.LOGTAIL_SOURCE_TOKEN }}

            CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
            
            EOF

            docker compose --project-name pramaan pull
            docker compose --project-name pramaan up -d --remove-orphans

            docker image prune -f
